version: "3.8"
services: 
  frontend:  
      build: ./frontend 
      environment:
         VITE_BACKEND_API_KEY: http://backend:8080/api/users
      ports: 
          - "80:80"
      depends_on: 
           - backend
           - mongodb
  backend: 
      build: ./backend
      environment: 
        frontend_port: http://frontend:80 
        PORT: 8080 
        MONGO_URI: mongodb://admin:Password%401234@mongodb:27017/users
      ports:
         - "8080:8080"
      depends_on: 
           - mongodb
  mongodb: 
      image: mongo:latest 
      environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: password 
      ports: 
        - "27017:27017"
