apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: manage
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  selector:
    matchLabels:
      app: backend-pods
  template:
    metadata:
      name: backend-pod
      namespace: manage
      labels:
        app: backend-pods
    spec:
      containers:
        - name: backend
          image: rajsoni968392/frontend-office-user-manage:latest
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: secret-backend
                  key: MONGO_URI
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: config-backend-api
                  key: PORT
