apiVersion: v1
kind: Secret
metadata:
  name: secret-backend
  namespace: manage
type: Opaque
data:
  MONGO_URI: mongodb+srv://rajsoni968392_db_user:rbgvQOYXh0dwrF1B@cluster0.fpc7xb3.mongodb.net/?appName=Cluster0
