apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJyYWpzb25pOTY4MzkyIiwicGFzc3dvcmQiOiJSYWpzb25pQDAzMDcyMDA1IiwiYXV0aCI6ImNtRnFjMjl1YVRrMk9ETTVNanBTWVdwemIyNXBRREF6TURjeU1EQTEifX19
kind: Secret
metadata:
  name: dockerhub-secret
  namespace: manage
type: kubernetes.io/dockerconfigjson
