apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: manage
spec:
  type: NodeSelector
  selector:
    app: frontend-pods
  ports:
    port: 80
    targetPort: 80
    NodePort: 30000
