apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: manage
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-pods
  template:
    metadata:
      name: frontend-pod
      namespace: manage
      labels:
        app: frontend-pods
    spec:
      containers:
        - name: frontend
          image: rajsoni968392/frontend-office-user-manage:latest
          env:
            - name: VITE_BACKEND_API_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-frontend-vite
                  key: backend_api_key
