apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: manage
spec:
  type: NodePort
  selector:
    app: mongo-pod
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 32767
