apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistentvolume
  namespace: manage
spec:
  capacity:
    storage: "10Gi"
  storageClassName: standard
  accessModes: ["ReadWriteOnce"]
  hostPath:
    path: /mnt/data
  persistentVolumeReclaimPolicy: Retain
