apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistentvolumeclaim
  namespace: manage
spec:
  resources:
    requests:
      storage: "10Mi"
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
