name: "compose-run"
on:
  workflow_dispatch:
jobs:
  task:
    runs-on: ubuntu-latest
    steps:
      - name: checkcode
        uses: actions/checkout@v4
      - name: docker compose
        run: |
          docker compose up -d 
          docker compose start 
          docker compose ps 
          sleep 30


